//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFB2TEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbNF_B2TEntity : DbContext
    {
        public dbNF_B2TEntity()
            : base("name=dbNF_B2TEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCidade> tblCidades { get; set; }
        public DbSet<tblCliente> tblClientes { get; set; }
        public DbSet<tblDescricaoNota> tblDescricaoNotas { get; set; }
        public DbSet<tblInformacaoBancaria> tblInformacaoBancarias { get; set; }
        public DbSet<tblNotaFiscal> tblNotaFiscals { get; set; }
        public DbSet<tblNotaFiscal_Retencao> tblNotaFiscal_Retencao { get; set; }
        public DbSet<tblRetencao> tblRetencaos { get; set; }
        public DbSet<tblTipoNota> tblTipoNotas { get; set; }
        public DbSet<tblUF> tblUFs { get; set; }
        public DbSet<tblUsuario> tblUsuarios { get; set; }
    }
}
