//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFB2TEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDescricaoNota
    {
        public int codDescricaoNota { get; set; }
        public int codNotaFiscal { get; set; }
        public string dcDetalheNota { get; set; }
        public int nuQuantidade { get; set; }
    
        public virtual tblNotaFiscal tblNotaFiscal { get; set; }
    }
}
