//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFB2TEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInformacaoBancaria
    {
        public tblInformacaoBancaria()
        {
            this.tblNotaFiscals = new HashSet<tblNotaFiscal>();
        }
    
        public int codInformacaoBancaria { get; set; }
        public int nuBanco { get; set; }
        public string noBanco { get; set; }
        public string nuAgencia { get; set; }
        public string nuContaCorrente { get; set; }
    
        public virtual ICollection<tblNotaFiscal> tblNotaFiscals { get; set; }
    }
}
