//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFB2TEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotaFiscal_Retencao
    {
        public int codNnotaFiscal { get; set; }
        public int codRetencao { get; set; }
        public decimal vlAliquota { get; set; }
    
        public virtual tblNotaFiscal tblNotaFiscal { get; set; }
        public virtual tblRetencao tblRetencao { get; set; }
    }
}
