//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFB2TEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotaFiscal
    {
        public tblNotaFiscal()
        {
            this.tblDescricaoNotas = new HashSet<tblDescricaoNota>();
            this.tblNotaFiscal_Retencao = new HashSet<tblNotaFiscal_Retencao>();
        }
    
        public int codNotaFiscal { get; set; }
        public int codCliente { get; set; }
        public int codTipoConta { get; set; }
        public int codInformacaoBancaria { get; set; }
        public int codUsuario { get; set; }
        public decimal vlUnitario { get; set; }
        public decimal vlTotal { get; set; }
        public decimal vlDeducaoLegal { get; set; }
        public System.DateTime dtEmissao { get; set; }
        public Nullable<decimal> vlBaseCalculoISS { get; set; }
        public Nullable<decimal> vlISS { get; set; }
        public string dcInformacaoComplementar { get; set; }
        public Nullable<int> nuControleFormulario { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
        public virtual ICollection<tblDescricaoNota> tblDescricaoNotas { get; set; }
        public virtual tblInformacaoBancaria tblInformacaoBancaria { get; set; }
        public virtual ICollection<tblNotaFiscal_Retencao> tblNotaFiscal_Retencao { get; set; }
        public virtual tblTipoNota tblTipoNota { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
