//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFB2TEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRetencao
    {
        public tblRetencao()
        {
            this.tblNotaFiscal_Retencao = new HashSet<tblNotaFiscal_Retencao>();
        }
    
        public int codRetencao { get; set; }
        public string dcRetencao { get; set; }
        public string sgRetencao { get; set; }
    
        public virtual ICollection<tblNotaFiscal_Retencao> tblNotaFiscal_Retencao { get; set; }
    }
}
