//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFB2TEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUF
    {
        public tblUF()
        {
            this.tblCidades = new HashSet<tblCidade>();
        }
    
        public int codUF { get; set; }
        public string dcUF { get; set; }
        public string sgUF { get; set; }
    
        public virtual ICollection<tblCidade> tblCidades { get; set; }
    }
}
